// Generated by scripts/design-registry.mjs; do not edit. Run `make design-registry`.
import type { ScreenModule } from "./screen";
import * as screen0 from "@/features/health/screens/S-00-health.screen";

export const screenModules: ScreenModule[] = [screen0];
export const variantNames: string[] = [];
