apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ledger-qa
resources:
  - ../../base
images:
  - name: asia-south1-docker.pkg.dev/example-ledger-shared/ledger/ledger-api
    newTag: "1.14.2"
  - name: asia-south1-docker.pkg.dev/example-ledger-shared/ledger/ledger-worker
    newTag: "1.8.0"
