#!/usr/bin/env bash
# tests/unit/guard_readonly.sh: brg-guard readonly, the mode the read-only
# subagents (reviewer, security auditor, explorer, critic) run their Bash
# through. Only inspection commands pass; anything that writes a file, runs a
# build, or reaches a mutating git subcommand is refused. Blocked strings are
# assembled at run time so the file never holds one on a single line.
set -u
. "$(dirname "$0")/../lib/assert.sh"
H="sh"; P="pu$H"

table="$(tmpdir)/rows"
row() { printf '%s\t%s\n' "$1" "$2" >> "$table"; }

# --- reads that must pass
row ALLOW "git diff HEAD~1"
row ALLOW "git diff --stat origin/main...HEAD"
row ALLOW "git log --oneline -20"
row ALLOW "git show HEAD:README.md"
row ALLOW "git status --porcelain"
row ALLOW "git blame -L 1,20 src/main.go"
row ALLOW "git ls-files '*.go'"
row ALLOW "git rev-parse --show-toplevel"
row ALLOW "git branch --show-current"
row ALLOW "git branch -a"
row ALLOW "git stash list"
row ALLOW "git remote -v"
row ALLOW "git config --get core.hooksPath"
row ALLOW "git tag -l"
row ALLOW "git diff 2>&1 | head -50"
row ALLOW "ls -la src"
row ALLOW "cat Makefile"
row ALLOW "head -40 src/app.py; tail -5 log.txt"
row ALLOW "wc -l src/*.go"
row ALLOW "grep -rn TODO src | sort | uniq -c"
row ALLOW "rg -n 'func main' --type go"
row ALLOW "find . -name '*.ts' -not -path '*/node_modules/*'"
row ALLOW "sed -n '1,40p' file"
row ALLOW "sed 's/a/b/' file"
row ALLOW "awk '{print \$1}' file"
row ALLOW "jq -r .name package.json"
row ALLOW "diff a b"
row ALLOW "stat -c %a .env"
row ALLOW "go test ./..."
row ALLOW "go vet ./..."
row ALLOW "go list ./..."
row ALLOW "make check"
row ALLOW "make -n build"
row ALLOW "pnpm test"
row ALLOW "npm ls --depth 0"
row ALLOW "uv run pytest -q"
row ALLOW "git --no-pager log"
row ALLOW "git -C sub log --oneline"
row ALLOW "sort -n f"
row ALLOW "date +%Y"
row ALLOW "date -d yesterday +%s"
row ALLOW "rg -n x --type go"
row ALLOW "npm run lint"
row ALLOW "awk '\$1 > 5 {print \$2}' f"
row ALLOW "ls 2>&1 | head"
row ALLOW "git grep -n TODO"
row ALLOW "sh -c 'git diff'"
row ALLOW "cat f > /dev/null"
row ALLOW "grep x f 2>/dev/null"
row ALLOW "cd src && ls"
row ALLOW "ls & cat f"
row ALLOW "echo hello"
row ALLOW "true"

# --- writes and mutations that must be refused
row DENY "git $P"
row DENY "git commit -m x"
row DENY "git add ."
row DENY "git checkout -b x"
row DENY "git switch x"
row DENY "git stash"
row DENY "git stash drop"
row DENY "git branch -D x"
row DENY "git tag v1"
row DENY "git config user.name x"
row DENY "git remote set-url origin x"
row DENY "git worktree add x"
row DENY "rm -rf dist"
row DENY "rm file"
row DENY "touch x"
row DENY "mkdir -p x"
row DENY "mv a b"
row DENY "cp a b"
row DENY "chmod +x f"
row DENY "sed -i 's/a/b/' file"
row DENY "sed -i.bak 's/a/b/' file"
row DENY "find . -name '*.log' -delete"
row DENY "find . -name '*.go' -exec rm {} +"
row DENY "echo hi > out.txt"
row DENY "cat a >> b"
row DENY "cat f &> out"
row DENY "cmd >&2"
row DENY "tee out < in"
row DENY "go build ./..."
row DENY "go mod tidy"
row DENY "make build"
row DENY "make deploy"
row DENY "pnpm install"
row DENY "pnpm run build"
row DENY "npm publish"
row DENY "uv add requests"
row DENY "python3 -c 'open(\"x\",\"w\").write(\"1\")'"
row DENY "python3 -c 'import os; os.system(\"ls\")'"
row DENY "python3 script.py"
row DENY "node -e 'require(\"fs\").writeFileSync(\"a\",\"1\")'"
row DENY "sh -c 'touch x'"
row DENY "bash -c 'rm -rf dist'"
row DENY "eval 'touch x'"
row DENY "xargs rm < list"
row DENY "docker build ."
row DENY "terraform plan"
row DENY "curl https://example.com"
row DENY "ssh host ls"
row DENY ""
row DENY "   "
row DENY "__BRG_UNPARSED__"
# python and node one-liners are no longer read-only
row DENY "python3 -c 'print(1)'"
row DENY "node -e 'console.log(1)'"
row DENY "python3 -c \"open('x','a')\""
row DENY "echo hi>out.txt"
row DENY "echo hi>>out.txt"
row DENY "ls 2>err.txt"
row DENY "ls >&out.txt"
row DENY "sort -o out x"
row DENY "sort --output=out x"
row DENY "git diff --output=x"
row DENY "git log --output x"
row DENY "git grep -Ovim x"
row DENY "find . -fls x"
row DENY "find . -fprintf x '%p'"
row DENY "awk '{print > \"x\"}' f"
row DENY "awk '{print | \"$H\"}' f"
row DENY "awk 'BEGIN{system(\"ls\")}'"
row DENY "awk -f prog.awk f"
row DENY "echo x | $H"
row DENY "bash evil.sh"
row DENY "rg --pre cat x"
row DENY "rg --pre=cat x"
row DENY "go test -exec rm ./..."
row DENY "go test -toolexec=x ./..."
row DENY "go test -coverprofile=c.out ./..."
row DENY "go env -w GOFLAGS=x"
row DENY "npm run clean"
row DENY "npm exec x"
row DENY "date -s now"
row DENY "date 010100002030"
row DENY "uniq in out"
row DENY "tree -o out"
row DENY "yq -i '.a=1' f.yaml"
row DENY "git -c core.pager=vim log"

rows=0; denies=0; allows=0
t_begin "readonly table"
while IFS="$(printf '\t')" read -r expect cmd; do
  rows=$((rows+1))
  case "$expect" in
    DENY)  denies=$((denies+1)); assert_exit 2 bash "$GUARD" readonly "$cmd";;
    ALLOW) allows=$((allows+1)); assert_exit 0 bash "$GUARD" readonly "$cmd";;
  esac
done < "$table"
t_end

t_begin "readonly refusal names the reason"
assert_exit 2 bash "$GUARD" readonly "rm -rf dist"
assert_contains "$T_OUT" "not a read-only command"
assert_exit 2 bash "$GUARD" readonly "sed -i 's/a/b/' f"
assert_contains "$T_OUT" "sed -i writes files"
assert_exit 2 bash "$GUARD" readonly "echo hi > out.txt"
assert_contains "$T_OUT" "writes a file"
t_end

t_begin "command mode is unchanged by the readonly rules"
assert_exit 0 bash "$GUARD" command "echo hi > out.txt"
assert_exit 0 bash "$GUARD" command "rm -rf dist"
assert_exit 0 bash "$GUARD" command "go build ./..."
t_end

echo "guard_readonly: $rows rows ($denies deny, $allows allow)"
t_summary
