#!/usr/bin/env python3
"""Record the terminal sessions the developer guide replays.

Each session is a list of real commands run against this checkout of the
kit, in a throwaway directory, with a neutral git identity and a tracker of
none. Every line of output is kept with the time it arrived, so the guide
replays the real thing at the real pace (long pauses are shortened on
replay, never the text). Home and scratch paths are rewritten to `~` and
`/work` so nothing about the recording machine is published.

    python3 devguide/scripts/record.py            record every session
    python3 devguide/scripts/record.py guard      record one

Writes devguide/src/data/recordings.json. Unlike internals.json this file
is not regenerated by `make lint-docs`: a recording is a dated observation,
so re-record it when the behaviour it shows changes. Fails when a session
recorded zero lines of output."""

import json
import os
import pathlib
import selectors
import shutil
import subprocess
import sys
import tempfile
import time

KIT = pathlib.Path(__file__).resolve().parents[2]
OUT = KIT / "devguide" / "src" / "data" / "recordings.json"
HOME = str(pathlib.Path.home())

# The words are assembled so this file never contains a publish command as
# text: the kit's own guard reads Bash commands, not Python files, but a
# reader grepping for them should find only the guard's table.
PUSH = "git " + "push origin main"
AMEND = "git commit " + "--amend --no-edit"
DEPLOY = "kubectl " + "apply -f k8s/"


def sessions(work):
    g = "bash plugins/bearing/bin/brg-guard"
    return {
        "guard": {
            "title": "The guard reads a command before it runs",
            "cwd": str(KIT),
            "steps": [
                f'{g} command "git status --short"',
                f'{g} command "{PUSH}"',
                f"{g} command 'env GIT_TRACE=1 {PUSH}'",
                f"{g} command 'echo ok && {AMEND}'",
                f'{g} command "rm -rf ../elsewhere"',
                f"{g} command 'git $SUB origin'",
                f'{g} command "{DEPLOY}"',
                f"{g} --verbs | wc -l",
            ],
        },
        "hooks": {
            "title": "A hook is a six-line adapter over the guard",
            "cwd": str(KIT),
            "steps": [
                "cat plugins/bearing/hooks/scripts/block-publish.sh",
                'printf \'%s\' \'{"tool_input":{"command":"make check"}}\' | bash plugins/bearing/hooks/scripts/block-publish.sh; echo "exit $?"',
                'printf \'%s\' \'{"tool_input":{"command":"'
                + PUSH
                + '"}}\' | bash plugins/bearing/hooks/scripts/block-publish.sh; echo "exit $?"',
            ],
        },
        "scaffold": {
            "title": "A new repository from the templates",
            "cwd": work,
            "steps": [
                f"bash {KIT}/plugins/bearing/bin/brg-scaffold go-api InvoiceService --dir {work}/InvoiceService --host gitlab --tracker none",
                "cd InvoiceService && git config core.hooksPath && git status --short | wc -l",
                "cd InvoiceService && head -8 CLAUDE.md",
                "cd InvoiceService && ls -A",
                "cd InvoiceService && head -12 AGENTS.md",
                "cd InvoiceService && ls .githooks .claude .claude/rules",
            ],
        },
        "adopt": {
            "title": "Adopting a repository that already exists, twice",
            "cwd": work,
            "steps": [
                'mkdir legacy && cd legacy && git init -q -b main && printf \'{"name":"legacy","scripts":{"test":"vitest"}}\\n\' > package.json && printf \'# Legacy\\n\' > README.md && git add -A && git commit -qm \'chore: initial\' && echo ready',
                f"cd legacy && bash {KIT}/plugins/bearing/bin/brg-adopt --stack react-web --host github --tracker none",
                f"cd legacy && bash {KIT}/plugins/bearing/bin/brg-adopt --stack react-web --host github --tracker none | tail -3",
            ],
        },
        "autopilot": {
            "title": "Autopilot holds the order; the gates are checked on disk",
            "cwd": work,
            "steps": [
                f"python3 {KIT}/plugins/bearing/bin/brg-autopilot stages",
                "mkdir pilot && cd pilot && git init -q -b main && git commit -q --allow-empty -m 'chore: start' && echo ready",
                f"cd pilot && python3 {KIT}/plugins/bearing/bin/brg-autopilot start 'Invoices can be exported as CSV'",
                f"cd pilot && python3 {KIT}/plugins/bearing/bin/brg-autopilot next",
                f"cd pilot && python3 {KIT}/plugins/bearing/bin/brg-autopilot done repo",
                f"cd pilot && python3 {KIT}/plugins/bearing/bin/brg-autopilot status | head -20",
            ],
        },
        "check": {
            "title": "make check, the kit's own gate",
            "cwd": str(KIT),
            "steps": ["make check"],
        },
        "tracker": {
            "title": "One command surface over every tracker",
            "cwd": str(KIT),
            "steps": [
                "bash plugins/bearing/bin/brg-tracker config",
                "bash plugins/bearing/bin/brg-tracker create --type story --title 'Export invoices'; echo \"exit $?\"",
            ],
        },
    }


def scrub(text, work):
    return text.replace(work + "/.home", "~").replace(work, "/work").replace(str(KIT), "~/bearing").replace(HOME, "~")


def run(cmd, cwd, env, work):
    t0 = time.monotonic()
    p = subprocess.Popen(
        ["bash", "-c", cmd],
        cwd=cwd,
        env=env,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
    )
    sel = selectors.DefaultSelector()
    sel.register(p.stdout, selectors.EVENT_READ)
    lines, buf = [], b""
    while True:
        if sel.select(timeout=0.2):
            chunk = os.read(p.stdout.fileno(), 65536)
            if not chunk:
                break
            buf += chunk
            while b"\n" in buf:
                line, buf = buf.split(b"\n", 1)
                lines.append(
                    [
                        round(time.monotonic() - t0, 2),
                        scrub(line.decode("utf-8", "replace"), work),
                    ]
                )
        elif p.poll() is not None and not sel.select(timeout=0):
            break
    if buf:
        lines.append(
            [
                round(time.monotonic() - t0, 2),
                scrub(buf.decode("utf-8", "replace"), work),
            ]
        )
    code = p.wait()
    return {
        "cmd": scrub(cmd, work),
        "code": code,
        "ms": int((time.monotonic() - t0) * 1000),
        "out": lines,
    }


def main():
    only = set(sys.argv[1:])
    data = json.loads(OUT.read_text()) if OUT.exists() else {}
    work = tempfile.mkdtemp(prefix="bearing-rec-")
    fake_home = pathlib.Path(work) / ".home"
    (fake_home / ".config" / "bearing").mkdir(parents=True)
    envfile = fake_home / ".config" / "bearing" / "bearing.env"
    envfile.write_text("BEARING_TRACKER=none\nBEARING_GIT_HOST=gitlab\n")
    envfile.chmod(0o600)
    env = dict(os.environ)
    env.update(
        {
            "BEARING_ENV": str(envfile),
            "GIT_AUTHOR_NAME": "Bearing demo",
            "GIT_AUTHOR_EMAIL": "demo@example.com",
            "GIT_COMMITTER_NAME": "Bearing demo",
            "GIT_COMMITTER_EMAIL": "demo@example.com",
            "GIT_CONFIG_GLOBAL": str(fake_home / ".gitconfig"),
            "NO_COLOR": "1",
            "TERM": "dumb",
        }
    )
    (fake_home / ".gitconfig").write_text("[init]\n\tdefaultBranch = main\n")
    try:
        for key, s in sessions(work).items():
            if only and key not in only:
                continue
            steps = [run(c, s["cwd"], env, work) for c in s["steps"]]
            n = sum(len(st["out"]) for st in steps)
            if not n:
                sys.exit(f"record: {key} produced 0 lines, nothing recorded")
            data[key] = {
                "title": s["title"],
                "cwd": scrub(s["cwd"], work),
                "recorded": time.strftime("%Y-%m-%d"),
                "steps": steps,
            }
            print(f"record: {key}: {len(steps)} commands, {n} lines")
    finally:
        shutil.rmtree(work, ignore_errors=True)
    OUT.write_text(json.dumps(data, indent=1, ensure_ascii=False) + "\n")
    print(f"record: {len(data)} sessions in {OUT.relative_to(KIT)}")


if __name__ == "__main__":
    main()
